version: '3.8'
services:
  service1:
    build:
      context: .
      target: service1
      dockerfile: DockerFIle
    ports:
      - 3000:3000
  service2:
    build:
      context: .
      target: service2
      dockerfile: DockerFIle
    ports:
      - 3001:3001
  service3:
    build:
      context: .
      target: service3
      dockerfile: DockerFIle
    ports:
      - 3002:3002