FROM node:16-alpine3.14  as service1
WORKDIR /armphanu
COPY ./package.json .
RUN npm install
COPY . .
CMD [ "npm", "run", "service1" ]

FROM node:16-alpine3.14  as service2
WORKDIR /armphanu
COPY ./package.json .
RUN npm install
COPY . .
CMD [ "npm", "run", "service2" ]

FROM node:16-alpine3.14  as service3
WORKDIR /armphanu
COPY ./package.json .
RUN npm install
COPY . .
CMD [ "node", "service3.js" ]
